//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Res_Tab
    {
        public int O_ID { get; set; }
        public string O_Name { get; set; }
        public string O_Desc { get; set; }
        public string O_Price { get; set; }
        public string O_Type { get; set; }
        public string O_Stat { get; set; }
        public string O_Cate { get; set; }
    }
}
